
services:
  kafka-broker-1:
    image: bitnami/kafka:latest
    container_name: kafka-broker-1
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_KRAFT_CLUSTER_ID: 7Dvn0OLMQo-bg4qmCmflVg
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9094:9094"
    networks:
      - kafka-network
  kafka-broker-2:
    image: bitnami/kafka:latest
    container_name: kafka-broker-2
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9095
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-2:9092,EXTERNAL://localhost:9095
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_KRAFT_CLUSTER_ID: 7Dvn0OLMQo-bg4qmCmflVg
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9095:9095"
    networks:
      - kafka-network
  kafka-broker-3:
    image: bitnami/kafka:latest
    container_name: kafka-broker-3
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_NODE_ID: 3
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9096
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-3:9092,EXTERNAL://localhost:9096
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_KRAFT_CLUSTER_ID: 7Dvn0OLMQo-bg4qmCmflVg
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9096:9096"
    networks:
      - kafka-network
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
      KAFKA_CLUSTERS_0_READONLY: false
      KAFKA_CLUSTERS_0_TOPIC_AUTO_CREATE: true
    ports:
      - "8080:8080"
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge


# services:
#   controller-1:
#     image: apache/kafka:latest
#     container_name: controller-1
#     environment:
#       KAFKA_NODE_ID: 1
#       KAFKA_PROCESS_ROLES: controller
#       KAFKA_LISTENERS: CONTROLLER://:9093
#       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#       KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#       KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

#   controller-2:
#     image: apache/kafka:latest
#     container_name: controller-2
#     environment:
#       KAFKA_NODE_ID: 2
#       KAFKA_PROCESS_ROLES: controller
#       KAFKA_LISTENERS: CONTROLLER://:9093
#       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#       KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#       KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

#   controller-3:
#     image: apache/kafka:latest
#     container_name: controller-3
#     environment:
#       KAFKA_NODE_ID: 3
#       KAFKA_PROCESS_ROLES: controller
#       KAFKA_LISTENERS: CONTROLLER://:9093
#       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#       KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#       KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

#   broker-1:
#     image: apache/kafka:latest
#     container_name: broker-1
#     ports:
#       - 29092:9092
#     environment:
#       KAFKA_NODE_ID: 4
#       KAFKA_PROCESS_ROLES: broker
#       KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
#       KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-1:19092,PLAINTEXT_HOST://localhost:29092'
#       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#       KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#       KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#     depends_on:
#       - controller-1
#       - controller-2
#       - controller-3

#   broker-2:
#     image: apache/kafka:latest
#     container_name: broker-2
#     ports:
#       - 39092:9092
#     environment:
#       KAFKA_NODE_ID: 5
#       KAFKA_PROCESS_ROLES: broker
#       KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
#       KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-2:19092,PLAINTEXT_HOST://localhost:39092'
#       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#       KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#       KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#     depends_on:
#       - controller-1
#       - controller-2
#       - controller-3

#   broker-3:
#     image: apache/kafka:latest
#     container_name: broker-3
#     ports:
#       - 49092:9092
#     environment:
#       KAFKA_NODE_ID: 6
#       KAFKA_PROCESS_ROLES: broker
#       KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
#       KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-3:19092,PLAINTEXT_HOST://localhost:49092'
#       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#       KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#       KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#     depends_on:
#       - controller-1
#       - controller-2
#       - controller-3

#   kafka-ui:
#     image: provectuslabs/kafka-ui:latest
#     container_name: kafka-ui
#     environment:
#       KAFKA_CLUSTERS_0_NAME: local-cluster
#       KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: controller-1:9092,controller-2:9092,controller-3:9092
#       KAFKA_CLUSTERS_0_READONLY: false
#       KAFKA_CLUSTERS_0_TOPIC_AUTO_CREATE: true
#     ports:
#       - "8080:8080"
#     depends_on:
#       - controller-1
#       - controller-2
#       - controller-3
#     networks:
#       - kafka-network

# networks:
#   kafka-network:
#     driver: bridge